### ISSUE TITLE
[FEATURE REQ]: Make gaze master icons

### ISSUE THREAD

**Issue by okawo80085** [HoboVR-Labs/issue_tracker#15]

**Comment by Minothor** [comment]
SVG: ![GazeMaster_suggestion-1](https://user-images.githubusercontent.com/2125437/162587315-a257b3d8-2386-4d8b-8c67-94bce3b4db29.svg)
PNG: ![GM-icon](https://user-images.githubusercontent.com/2125437/162587316-4434ce85-9572-49c8-b5dd-e2e76d4cac8f.png)
PNG-Mask: ![GM-icon-mask](https://user-images.githubusercontent.com/2125437/162625836-1b151308-150c-4915-879b-fdea5244a44e.png)

**Comment by okawo80085** [comment]
Icon requirements: https://www.hobovrlabs.org/docs/html/openvr/introduction.html#status-icons

New icons:
> *in progress*

**Comment by VerscheldeAlynne** [comment]
![whiteShiteMask](https://user-images.githubusercontent.com/43439546/163680866-2eef4938-8fac-4bcb-91f8-d8f3841015b9.svg)
![WhiteStrokeShiteMask](https://user-images.githubusercontent.com/43439546/163680868-b9b6bd3d-1d37-47bc-8089-0324a1430c1d.svg)
![blackShiteMask](https://user-images.githubusercontent.com/43439546/163680869-7226d19a-3c2e-4371-bd5d-aae65b81b89b.svg)
![strokeShiteMask](https://user-images.githubusercontent.com/43439546/163680871-0c74bc6c-be8a-49e6-bea2-3fdac384aff9.svg)

**Comment by okawo80085** [comment]
> Icon requirements: https://www.hobovrlabs.org/docs/html/openvr/introduction.html#status-icons
> 
> New icons:
> 
> > _in progress_

New x4 res icons:
![gaze_master_error@4x b4bfb144](https://user-images.githubusercontent.com/43695253/163716905-1dddf54c-f2ea-416e-a414-94f4ed2d7723.png)
![gaze_master_error@4x](https://user-images.githubusercontent.com/43695253/163716906-f494e644-f552-4fb0-b861-defd42da5617.png)
![gaze_master_off@4x](https://user-images.githubusercontent.com/43695253/163716907-292cf1ee-ba1a-467a-9aea-7502bc990ca1.png)
![gaze_master_ready@4x b4bfb144](https://user-images.githubusercontent.com/43695253/163716908-9e170f63-6bd0-4b89-b63e-ebba6148240e.png)
![gaze_master_ready@4x](https://user-images.githubusercontent.com/43695253/163716909-113ff5d7-631a-4da3-9c00-17372815e788.png)
![gaze_master_ready_alert@4x b4bfb144](https://user-images.githubusercontent.com/43695253/163716910-08f26ea4-18f6-4864-912a-bbd575d97384.png)
![gaze_master_ready_alert@4x](https://user-images.githubusercontent.com/43695253/163716911-a1d06380-2945-456d-a1ad-e2753ce627e8.png)
![gaze_master_ready_low@4x b4bfb144](https://user-images.githubusercontent.com/43695253/163716912-6522dd79-9b73-417e-9af8-6e7ec330dee5.png)
![gaze_master_ready_low@4x](https://user-images.githubusercontent.com/43695253/163716913-9e712420-5da1-4188-b6d2-31ebb9a4c903.png)
![gaze_master_searching@4x b4bfb144](https://user-images.githubusercontent.com/43695253/163716914-a260ce8a-4d72-49a8-890e-825d302eb8fb.gif)
![gaze_master_searching@4x](https://user-images.githubusercontent.com/43695253/163716915-3db56f2d-f727-42ba-8af9-1c21bff38262.gif)
![gaze_master_searching_alert@4x b4bfb144](https://user-images.githubusercontent.com/43695253/163716917-0a70d5be-ddfc-474c-b9b8-9cf6dbbe817e.gif)
![gaze_master_searching_alert@4x](https://user-images.githubusercontent.com/43695253/163716918-3a6c3109-ae1e-411c-87b6-bce1e56a0412.gif)
![gaze_master_standby@4x b4bfb144](https://user-images.githubusercontent.com/43695253/163716920-47e8b664-4adb-4846-96e5-0f80368dcf6a.png)
![gaze_master_standby@4x](https://user-images.githubusercontent.com/43695253/163716923-d189f593-1ba3-46ba-b6fe-94c175fd03a6.png)

Final icons will be scaled down to x2 and x1 res to conform with icons requirements.
